# mongo can be pulled from the docker hub
# thoughtcore-node is built from the Dockerfile in the current directory using node from docker hub
# insight is built from the Dockerfile in the packages/insight directory using node from docker hub
# thought is built from the src repo using the ubuntu image
# Network name becomes the "name" + "_" + "insight-services"
name: thoughtcore
services:
  mongo:
    container_name: mongo
    image: mongo:8.0.3-noble
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - insight-services

  thoughtcore-node:
    container_name: thoughtcore-node
    build: 
      context: .
      dockerfile: ./docker/thoughtcore-node/Dockerfile2
    image: thoughtcore-node
    ports:
      - 8100:8100
      - 3004:3004
    links:
      - mongo
    environment:
      - DB_HOST=mongo
      - THOUGHTCORE_NODE_HTTP_PORT=3004
    env_file: .env
    restart: unless-stopped
    networks:
      - insight-services

  insight:
    container_name: insight
    build: 
      context: .
      dockerfile: ./docker/insight/Dockerfile2
    image: insight
    ports:
      - 3000:3000
    links:
      - thoughtcore-node
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_URL=thoughtcore-node
    restart: unless-stopped
    networks:
      - insight-services

  thoughtd:
    container_name: thoughtd
    build:
      context: .
      dockerfile: ./docker/thoughtd/Dockerfile
    image: thoughtd:0.18.3
    volumes:
      - thoughtd-data:/data
    ports:
      - 10617:10617
      - 10618:10618
      - 11617:11617
      - 11618:11618
    restart: unless-stopped
    networks:
      - insight-services

volumes:
  mongo-data:
  thoughtd-data:

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  insight-services:
    driver: bridge