version: "3"

services:

  db:
    image: mongo:3.6.23

  thought:
    image: ruimarinho/thought-core:24
    command: -printtoconsole -regtest=1 -txindex=0 -listen=1 -server=1 -dnsseed=0 -upnp=0 -port=8332 -rpcport=8333 -rpcallowip=0.0.0.0/0 -rpcbind=0.0.0.0 -rpcuser=thoughtcorenodetest -rpcpassword=local321 -fallbackfee=0.00001

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
